# Hadolint configuration
# https://github.com/hadolint/hadolint

# Ignore specific rules
ignored:
  - DL3008  # Pin versions in apt-get install (we use debian stable)
  - DL3009  # Delete apt lists after installing (already handled)
  - DL3059  # Multiple consecutive RUN commands (needed for cache layers)

# Trusted registries
trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io

# Failure threshold
failure-threshold: warning

# Inline ignore
# Use # hadolint ignore=DL3008 above specific lines if needed
